name: Publish to NPM

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run tests
        run: pnpm run test
        
      - name: Build project
        run: pnpm run build
        
      - name: Verify package
        run: pnpm pack
        
      - name: Publish to NPM
        run: |
          echo "Publishing to NPM..."
          pnpm publish --no-git-checks
          echo "Successfully published to NPM!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes the latest changes to effect-schema-geojson.
            
            ## Installation
            
            ```bash
            pnpm add effect-schema-geojson effect
            ```
            
            ## Links
            
            - [NPM Package](https://www.npmjs.com/package/effect-schema-geojson)
            - [GitHub Repository](https://github.com/tvshevchuk/effect-schema-geojson)
          draft: false
          prerelease: false
          
      - name: Deployment Summary
        run: |
          echo "🎉 Deployment Complete!"
          echo "======================="
          echo "• NPM: https://www.npmjs.com/package/effect-schema-geojson"
          echo "• GitHub Release created for ${{ github.ref_name }}"
          echo ""
          echo "Installation command:"
          echo "pnpm add effect-schema-geojson effect"
          echo ""
          echo "Thank you for using Effect Schema GeoJSON! 🚀"
